# app/models/config_template_model.py
from pydantic import BaseModel, Field
from typing import Dict
from datetime import datetime

class ConfigModel(BaseModel):
    j2_template: str = Field(
        ...,
        title="Jinja2 Template",
        description="Enter your Jinja2 template here",
    )

    json_data: Dict = Field(
        ...,
        title="JSON Data",
        description="Enter JSON values for the Jinja2 template",
    )

class ConfigToTemplateSuccessResponse(BaseModel):
    jinja2_template: str = Field(..., description="The generated Jinja2 template.")
    json_variables: Dict = Field(..., description="The extracted JSON variables.")

class ConfigToTemplateErrorResponse(BaseModel):
    error: str = Field(..., description="Error message if the conversion failed.")

class ConfigTemplate(BaseModel):
    template_name: str = Field(..., description="Unique name for the template (Device_name + timestamp)")
    username: str = Field(..., description="Username of the user who created the template")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of template creation")
    device_name: str = Field(..., description="Device name extracted by LLM")
    input_configuration: str = Field(..., description="Original network configuration input")
    jinja2_template: str = Field(..., description="Jinja2 template generated by LLM")
    json_variables: Dict = Field(..., description="JSON variables extracted by LLM")
    
    class Config:
        orm_mode = True  
        
from pydantic import BaseModel, Field
from typing import Optional, Dict
from datetime import datetime

class Config(BaseModel):
    """
    Represents a configuration in the database.
    """
    id: Optional[str] = Field(alias='_id', default=None)
    name: str = Field(..., description="Configuration name (unique)")
    customer: str = Field(..., description="Customer name (must exist in customers collection)")
    config_data: Dict = Field(..., description="JSON object containing the configuration data")
    created_by: str = Field(..., description="Username of the creator")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    status: Optional[str] = Field(default="active", description="Status of the configuration") # Add status

    class Config:
        orm_mode = True
        allow_population_by_field_name = True